//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFlow.Tasks {
    
    
    public partial class CalendarView {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new ProjectFlow.Tasks.TaskNested Master {
            get {
                return ((ProjectFlow.Tasks.TaskNested)(base.Master));
            }
        }
    }
}
