//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFlow
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IssueTB()
        {
            this.CommentForIssueTBs = new HashSet<CommentForIssueTB>();
            this.PollingTBs = new HashSet<PollingTB>();
        }
    
        public string issueID { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int createdBy { get; set; }
        public int taskID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentForIssueTB> CommentForIssueTBs { get; set; }
        public virtual TasksTB TasksTB { get; set; }
        public virtual TeamMemberTB TeamMemberTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PollingTB> PollingTBs { get; set; }
    }
}
