//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFlow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polling
    {
        public int pollingID { get; set; }
        public int solutionID { get; set; }
        public int voterID { get; set; }
        public Nullable<bool> vote { get; set; }
    
        public virtual Solution Solution { get; set; }
        public virtual TeamMember TeamMember { get; set; }
    }
}
