//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFlow
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTeamsTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectTeamsTB()
        {
            this.TasksTBs = new HashSet<TasksTB>();
            this.TeamMemberTBs = new HashSet<TeamMemberTB>();
        }
    
        public int teamID { get; set; }
        public string teamName { get; set; }
        public string teamDescription { get; set; }
        public int projectID { get; set; }
    
        public virtual ProjectTB ProjectTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TasksTB> TasksTBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamMemberTB> TeamMemberTBs { get; set; }
    }
}
