//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFlow
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectFlowEntities : DbContext
    {
        public ProjectFlowEntities()
            : base("name=ProjectFlowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CommentForIssueTB> CommentForIssueTBs { get; set; }
        public virtual DbSet<IssueTB> IssueTBs { get; set; }
        public virtual DbSet<PollingTB> PollingTBs { get; set; }
        public virtual DbSet<ProjectTB> ProjectTBs { get; set; }
        public virtual DbSet<ProjectTeamsTB> ProjectTeamsTBs { get; set; }
        public virtual DbSet<RoleTB> RoleTBs { get; set; }
        public virtual DbSet<TaskAllocationTB> TaskAllocationTBs { get; set; }
        public virtual DbSet<TasksTB> TasksTBs { get; set; }
        public virtual DbSet<TeamMemberTB> TeamMemberTBs { get; set; }
        public virtual DbSet<UserTB> UserTBs { get; set; }
    }
}
