//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFlow
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomActionItem
    {
        public int actionItemID { get; set; }
        public string personName { get; set; }
        public string topic { get; set; }
        public string type { get; set; }
        public int roomID { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
