//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFlow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int scoreID { get; set; }
        public Nullable<double> proposal { get; set; }
        public Nullable<double> report { get; set; }
        public Nullable<double> reviewOne { get; set; }
        public Nullable<double> reviewTwo { get; set; }
        public Nullable<double> presentation { get; set; }
        public Nullable<double> test { get; set; }
        public Nullable<double> sdl { get; set; }
        public Nullable<double> participation { get; set; }
        public System.Guid UserId { get; set; }
        public string projectID { get; set; }
        public Nullable<int> teamID { get; set; }
        public Nullable<double> proposalG { get; set; }
        public Nullable<double> reportG { get; set; }
        public Nullable<double> presentationG { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ProjectTeam ProjectTeam { get; set; }
        public virtual Student Student { get; set; }
    }
}
