//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFlow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solution()
        {
            this.Pollings = new HashSet<Polling>();
        }
    
        public int solutionID { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public bool success { get; set; }
        public int issueId { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public System.Guid createdBy { get; set; }
        public bool votePublic { get; set; }
        public string associatedFile { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Issue Issue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Polling> Pollings { get; set; }
    }
}
