//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFlow
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskAllocationTB
    {
        public int ID { get; set; }
        public int memberID { get; set; }
        public int taskID { get; set; }
    
        public virtual TasksTB TasksTB { get; set; }
        public virtual TeamMemberTB TeamMemberTB { get; set; }
    }
}
