//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFlow
{
    using System;
    using System.Collections.Generic;
    
    public partial class WhiteboardSession
    {
        public System.Guid sessionID { get; set; }
        public string groupName { get; set; }
        public int teamID { get; set; }
        public System.DateTime creationDateTime { get; set; }
        public string strokesJsonPath { get; set; }
    
        public virtual ProjectTeam ProjectTeam { get; set; }
    }
}
