//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFlowUnitTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoiceRecording
    {
        public System.Guid UserId { get; set; }
        public string recordingName { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
